### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Sladerix** [GreenPonik/esp32-ota-wifi-ap-mode#1]
Hi!
How can I actually send the .bin file of the new firmware?

**Comment by MkLHX** [comment]
Hello, 
Did you  now something about OTA using ESP32?

**Comment by Sladerix** [comment]
Actually, I’m doing my researches right now… 
But I think I just realized that you are uploading the new code using the Arduino IDE, am I right?

**Comment by MkLHX** [comment]
Hi you can find here some information about OTA using arduino IDE
https://lastminuteengineers.com/esp32-ota-updates-arduino-ide/

**Comment by Sladerix** [comment]
oh thank you for pointing it out 😃
